# Generated by Django 4.0.6 on 2022-07-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='function33',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gothram', models.CharField(max_length=500)),
                ('LastName', models.CharField(max_length=500)),
                ('FirstName', models.CharField(max_length=500)),
                ('SpouceName', models.CharField(max_length=500)),
                ('child1', models.CharField(max_length=500)),
                ('child2', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
