# Generated by Django 4.0.6 on 2022-07-22 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ganesh', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='function33',
            new_name='donation',
        ),
    ]
