# Generated by Django 4.0.6 on 2022-07-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganesh', '0004_poojaevents_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='poojaevents',
            name='Time',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
